# -*- coding: utf-8 -*-
"""001_Variabili.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wagRIXTXUixzi13DzE5YigWkEceMNcsr

Esercizio 1
Dichiarare una variabile "nome" e assegnargli il tuo nome. Mandare a schermo.
"""

nome = "roberta"
print(nome)

"""Esercizio 2
Dichiarare una variabile "eta" e assegnargli la tua età. Mandare a schermo.
"""

eta = 26
print(eta)

"""Esercizio 3
Dichiarare una variabile "pi" e assegnargli il valore di pi greco (3,14159). Mandare a schermo.
"""

import math
pi = math.pi
print(pi)
type(pi)

"""Esercizio 4
Creare una variabile "lunghezza" e assegnargli un valore, quindi riassegnare la variabile a 15. Mandare a schermo.
"""

lunghezza = 10
lunghezza = 15
print (lunghezza)

"""Esercizio 5
Creare una variabile "nome_completo" e assegnargli una stringa contenente il tuo nome e cognome. Mandare a schermo
"""

nome_completo = "roberta perota"
print(nome_completo)

"""Altra modalità"""

nome = "roberta"
cognome = "perota"
nome_completo = nome + " " + cognome
print (nome_completo)

"""Esercizio 6
Creare una variabile "eta_futura" e assegnargli il valore dell'età che avrai tra 10 anni (utilizzando la variabile età già esistente). Mandare a schermo.
"""

eta_futura = eta + 10 #abbiamo usato la variabile eta che abbiamo creato prima
print(eta_futura)

"""Esercizio 7
Creare delle variabili "nome", "cognome" ed "anno_di_nascita" ed assegnargli i valori. Mandare a schermo in un unico print. Sovrascrivere tutte le variabili e rimandare a schermo una seconda volta.
"""

#non ho dichiarato nome e cognome perchè l'ho dichiarata precedentemente
anno_di_nascita = 1998
print (nome + " " + cognome + " " + str((anno_di_nascita)))

"""Esercizio 8
Creare una variabile eta_attuale e assegnargli il valore dell'età che hai attualmente, calcolandola in base all'anno corrente. Mandare a schermo eta_attuale
"""

anno_corrente = 2025
eta_attuale = (anno_corrente-anno_di_nascita)
print (eta_attuale)